from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(613, 528)
        MainWindow.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -30, 621, 151))
        self.frame.setStyleSheet("background-color: rgb(52, 165, 201);\n"
"color : rgb(255, 255, 255);\n"
"border-radius :30px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 140, 291, 171))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color : rgb(22, 71, 86);\n"
"border-radius :10px;\n"
"border: 1px solid rgb(52, 165, 201);")
        self.groupBox.setObjectName("groupBox")
        self.cancel = QtWidgets.QPushButton(self.groupBox)
        self.cancel.setGeometry(QtCore.QRect(10, 120, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("background-color: rgb(52, 165, 201);\n"
"color : rgb(255, 255, 255);\n"
"border-radius : 10px;")
        self.cancel.setObjectName("cancel")
        self.validated = QtWidgets.QPushButton(self.groupBox)
        self.validated.setGeometry(QtCore.QRect(149, 120, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.validated.setFont(font)
        self.validated.setStyleSheet("background-color: rgb(52, 165, 201);\n"
"color : rgb(255, 255, 255);\n"
"border-radius : 10px;")
        self.validated.setObjectName("validated")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color : rgb(22, 71, 86);\n"
"border: none;")
        self.label.setObjectName("label")
        self.input = QtWidgets.QTextEdit(self.groupBox)
        self.input.setGeometry(QtCore.QRect(10, 70, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input.setFont(font)
        self.input.setStyleSheet("border-radius : 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(52, 165, 201);")
        self.input.setObjectName("input")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(310, 140, 291, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("color : rgb(22, 71, 86);\n"
"border-radius :10px;\n"
"border: 1px solid rgb(52, 165, 201);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color : rgb(22, 71, 86);\n"
"border: none;")
        self.label_3.setObjectName("label_3")
        self.result = QtWidgets.QLabel(self.groupBox_2)
        self.result.setGeometry(QtCore.QRect(10, 70, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.result.setFont(font)
        self.result.setStyleSheet("border: none;")
        self.result.setText("")
        self.result.setObjectName("result")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 320, 591, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("color : rgb(22, 71, 86);\n"
"border-radius :10px;\n"
"border: 1px solid rgb(52, 165, 201);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.lblRoute = QtWidgets.QTextEdit(self.groupBox_3)
        self.lblRoute.setEnabled(False)
        self.lblRoute.setGeometry(QtCore.QRect(10, 30, 571, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblRoute.setFont(font)
        self.lblRoute.setStyleSheet("border-radius : 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(52, 165, 201);")
        self.lblRoute.setObjectName("lblRoute")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "203405 Antonio Martinez"))
        self.label_4.setText(_translate("MainWindow", "LOTES DE MEDICAMENTO"))
        self.label_2.setText(_translate("MainWindow", "AUTOMATA VERIFICADOR DE"))
        self.groupBox.setTitle(_translate("MainWindow", "Datos de entrada"))
        self.cancel.setText(_translate("MainWindow", "Cancelar"))
        self.validated.setText(_translate("MainWindow", "Validar"))
        self.label.setText(_translate("MainWindow", "Ingrese el lote del Medicamento"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Datos de salida"))
        self.label_3.setText(_translate("MainWindow", "Resultado de la Verificacion:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Ruta del recorrido del automata"))
        self.lblRoute.setPlaceholderText(_translate("MainWindow", "Esperando los datos de salida"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
